// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhr4YYmVAUk9G04MVnTpNSWJvarJ5_ty0',
    appId: '1:945144307616:web:131abeae88719b68848ec5',
    messagingSenderId: '945144307616',
    projectId: 'calee-7c212',
    authDomain: 'calee-7c212.firebaseapp.com',
    storageBucket: 'calee-7c212.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDHoA6kM4s-_TzvgRBaS-IDCjsHIQ-leI',
    appId: '1:945144307616:android:b997a83433378780848ec5',
    messagingSenderId: '945144307616',
    projectId: 'calee-7c212',
    storageBucket: 'calee-7c212.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3GQt2kaGr2YKX5f1lGrgZ-KYhF30vnW4',
    appId: '1:945144307616:ios:0f6d177e9fa0307f848ec5',
    messagingSenderId: '945144307616',
    projectId: 'calee-7c212',
    storageBucket: 'calee-7c212.appspot.com',
    iosBundleId: 'com.example.iitropar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3GQt2kaGr2YKX5f1lGrgZ-KYhF30vnW4',
    appId: '1:945144307616:ios:0f6d177e9fa0307f848ec5',
    messagingSenderId: '945144307616',
    projectId: 'calee-7c212',
    storageBucket: 'calee-7c212.appspot.com',
    iosBundleId: 'com.example.iitropar',
  );
}
